/// Full plan definition from `GET /membership/plans`.
class MembershipPlan {
  const MembershipPlan({
    required this.id,
    required this.code,
    required this.name,
    required this.description,
    required this.appRoleCode,
    required this.price,
    required this.durationDays,
    required this.isActive,
  });

  factory MembershipPlan.fromJson(Map<String, dynamic> json) {
    return MembershipPlan(
      id: json['id'] as int,
      code: json['code'] as String,
      name: json['name'] as String,
      description: json['description'] as String?,
      appRoleCode: json['app_role_code'] as String,
      price: (json['price'] as num).toInt(),
      durationDays: (json['duration_days'] as num).toInt(),
      isActive: json['is_active'] as bool,
    );
  }

  final int id;
  final String code;
  final String name;
  /// Comma-separated list of benefits, auto-generated by the backend from
  /// the plan's assigned permissions — not free text. Null/empty when the
  /// app role behind this plan has no permissions assigned yet.
  final String? description;
  final String appRoleCode;
  final int price;
  final int durationDays;
  final bool isActive;

  /// [description] split into individual benefit lines for display.
  List<String> get benefits {
    final desc = description;
    if (desc == null || desc.trim().isEmpty) return const [];
    return desc.split(',').map((s) => s.trim()).where((s) => s.isNotEmpty).toList();
  }
}

/// Lightweight plan reference embedded in user/select-plan/status responses
/// (just id/code/name, no price/duration).
class MembershipPlanRef {
  const MembershipPlanRef({required this.id, required this.code, required this.name, this.description});

  factory MembershipPlanRef.fromJson(Map<String, dynamic> json) {
    return MembershipPlanRef(
      id: json['id'] as int,
      code: json['code'] as String,
      name: json['name'] as String,
      description: json['description'] as String?,
    );
  }

  final int id;
  final String code;
  final String name;
  final String? description;
}
